export const trilhas = [
      {
    id: 1,
    nome: "Morro Botucaraí - Witeck",
    distancia: 3,
    nivel: 7,
    dificuldade: "Média",
    clima: 3,
    temperatura: "Até 25º C",
    local: "#",
    capacidade: 25,
    descricao: "#",
    cidade: "#",
    estado: "RS",
    imagem: "#",
    mapa: "#"
  },
  {
    id: 2,
    nome: "Mirante Pedras Brancas",
    distancia: 4.5,
    nivel: 4,
    dificuldade: "Fácil",
    clima: 3,
    temperatura: "Até 25º C",
    local: "#",
    capacidade: 28,
    descricao: "#",
    cidade: "#",
    estado: "RS",
    imagem: "#",
    mapa: "#"
  },
  {
    id: 3,
    nome: "Adelar e Rocha",
    distancia: 5,
    nivel: 4,
    dificuldade: "Fácil",
    clima: 2,
    temperatura: "< 20º C",
    local: "#",
    capacidade: 30,
    descricao: "#",
    cidade: "#",
    estado: "RS",
    imagem: "#",
    mapa: "#"
  },
  {
    id: 4,
    nome: "Cascata do Angico",
    distancia: 5,
    nivel: 5,
    dificuldade: "Fácil-média",
    clima: 3,
    temperatura: "Até 25º C",
    local: "#",
    capacidade: 25,
    descricao: "#",
    cidade: "#",
    estado: "RS",
    imagem: "#",
    mapa: "#"
  },
  {
    id: 5,
    nome: "Manoel Alves (Curta)",
    distancia: 5,
    nivel: 6,
    dificuldade: "Média",
    clima: 2,
    temperatura: "< 20º C",
    local: "#",
    capacidade: 30,
    descricao: "#",
    cidade: "#",
    estado: "RS",
    imagem: "#",
    mapa: "#"
  },
  {
    id: 6,
    nome: "Mirante da Garganta do Diabo",
    distancia: 5,
    nivel: 6,
    dificuldade: "Média",
    clima: 3,
    temperatura: "Até 25º C",
    local: "Fáceis/Médias",
    capacidade: 30,
    descricao: "#",
    cidade: "#",
    estado: "RS",
    imagem: "#",
    mapa: "#"
  },
  {
    id: 7,
    nome: "Morro do Elefante (Curta)",
    distancia: 5,
    nivel: 6,
    dificuldade: "Média",
    clima: 3,
    temperatura: "Até 25º C",
    local: "#",
    capacidade: 30,
    descricao: "#",
    cidade: "#",
    estado: "RS",
    imagem: "#",
    mapa: "#"
  },
  {
    id: 8,
    nome: "Pozzobon",
    distancia: 5,
    nivel: 2,
    dificuldade: "Fácil",
    clima: 1,
    temperatura: "< 26º C",
    local: "#",
    capacidade: 30,
    descricao: "#",
    cidade: "#",
    estado: "RS",
    imagem: "#",
    mapa: "#"
  },
  {
    id: 9,
    nome: "Circular Tiaguinho",
    distancia: 6,
    nivel: 8,
    dificuldade: "Difícil-média",
    clima: 1,
    temperatura: "< 26º C",
    local: "#",
    capacidade: 30,
    descricao: "#",
    cidade: "#",
    estado: "RS",
    imagem: "#",
    mapa: "#"
  },
  {
    id: 10,
    nome: "Guarda-Mor",
    distancia: 6,
    nivel: 4,
    dificuldade: "Fácil",
    clima: 2,
    temperatura: "< 20º C",
    local: "#",
    capacidade: 30,
    descricao: "#",
    cidade: "#",
    estado: "RS",
    imagem: "#",
    mapa: "#"
  },
  {
    id: 11,
    nome: "Moinho de Silveira",
    distancia: 6,
    nivel: 7,
    dificuldade: "Média",
    clima: 1,
    temperatura: "< 26º C",
    local: "#",
    capacidade: 25,
    descricao: "#",
    cidade: "#",
    estado: "RS",
    imagem: "#",
    mapa: "#"
  },
  {
    id: 12,
    nome: "Poço Azul",
    distancia: 6,
    nivel: 5,
    dificuldade: "Fácil-média",
    clima: 2,
    temperatura: "< 20º C",
    local: "#",
    capacidade: 30,
    descricao: "#",
    cidade: "#",
    estado: "RS",
    imagem: "#",
    mapa: "#"
  },
  {
    id: 13,
    nome: "Moinho de São Marinho",
    distancia: 7,
    nivel: 7,
    dificuldade: "Média",
    clima: 1,
    temperatura: "< 26º C",
    local: "#",
    capacidade: 28,
    descricao: "#",
    cidade: "#",
    estado: "RS",
    imagem: "#",
    mapa: "#"
  },
    {
    id: 14,
    nome: "Rasga Barba",
    distancia: 7,
    nivel: 7,
    dificuldade: "Média",
    clima: 1,
    temperatura: "< 26º C",
    local: "#",
    capacidade: 25,
    descricao: "#",
    cidade: "#",
    estado: "RS",
    imagem: "#",
    mapa: "#"
  },
  {
    id: 15,
    nome: "Rincão Bonito",
    distancia: 7,
    nivel: 8,
    dificuldade: "Difícil-média",
    clima: 1,
    temperatura: "< 26º C",
    local: "#",
    capacidade: 25,
    descricao: "#",
    cidade: "#",
    estado: "RS",
    imagem: "#",
    mapa: "#"
  },
  {
    id: 16,
    nome: "Zagaia (Curta)",
    distancia: 7,
    nivel: 6,
    dificuldade: "Fácil",
    clima: 2,
    temperatura: "< 20º C",
    local: "#",
    capacidade: 30,
    descricao: "#",
    cidade: "#",
    estado: "RS",
    imagem: "#",
    mapa: "#"
  },
  {
    id: 17,
    nome: "5 Lagos",
    distancia: 8,
    nivel: 7,
    dificuldade: "Média",
    clima: 1,
    temperatura: "< 26º C",
    local: "#",
    capacidade: 35,
    descricao: "#",
    cidade: "#",
    estado: "RS",
    imagem: "#",
    mapa: "#"
  },
  {
    id: 18,
    nome: "Cânion do Adelar",
    distancia: 8,
    nivel: 8,
    dificuldade: "Difícil-média",
    clima: 1,
    temperatura: "< 26º C",
    local: "#",
    capacidade: 25,
    descricao: "#",
    cidade: "#",
    estado: "RS",
    imagem: "#",
    mapa: "#"
  },
  {
    id: 19,
    nome: "Escondida",
    distancia: 8,
    nivel: 10,
    dificuldade: "Muito difícil",
    clima: 1,
    temperatura: "< 26º C",
    local: "#",
    capacidade: 20,
    descricao: "#",
    cidade: "#",
    estado: "RS",
    imagem: "#",
    mapa: "#"
  },
  {
    id: 20,
    nome: "Jabuticabeira",
    distancia: 8,
    nivel: 6,
    dificuldade: "Média",
    clima: 3,
    temperatura: "Até 25º C",
    local: "Fáceis",
    capacidade: 30,
    descricao: "#",
    cidade: "#",
    estado: "RS",
    imagem: "#",
    mapa: "#"
  },
  {
    id: 21,
    nome: "Salto Lava-Pés",
    distancia: 8,
    nivel: 8,
    dificuldade: "Difícil-média",
    clima: 1,
    temperatura: "< 26º C",
    local: "#",
    capacidade: 25,
    descricao: "#",
    cidade: "#",
    estado: "RS",
    imagem: "#",
    mapa: "#"
  },
  {
    id: 22,
    nome: "Taboão",
    distancia: 8,
    nivel: 7,
    dificuldade: "Média",
    clima: 2,
    temperatura: "< 20º C",
    local: "#",
    capacidade: 30,
    descricao: "#",
    cidade: "#",
    estado: "RS",
    imagem: "#",
    mapa: "#"
  },
  {
    id: 23,
    nome: "Cânion do Clécio",
    distancia: 8.5,
    nivel: 8,
    dificuldade: "Difícil-média",
    clima: 2,
    temperatura: "< 20º C",
    local: "#",
    capacidade: 25,
    descricao: "#",
    cidade: "#",
    estado: "RS",
    imagem: "#",
    mapa: "#"
  },
  {
    id: 24,
    nome: "Caminho dos Peregrinos Linha Base",
    distancia: 9,
    nivel: 6,
    dificuldade: "Média",
    clima: 3,
    temperatura: "Até 25º C",
    local: "Médias",
    capacidade: 30,
    descricao: "#",
    cidade: "#",
    estado: "RS",
    imagem: "#",
    mapa: "#"
  },
  {
    id: 25,
    nome: "Pompéia",
    distancia: 9,
    nivel: 4,
    dificuldade: "Fácil-média",
    clima: 3,
    temperatura: "Até 25º C",
    local: "#",
    capacidade: 40,
    descricao: "#",
    cidade: "#",
    estado: "RS",
    imagem: "#",
    mapa: "#"
  },
  {
    id: 26,
    nome: "Zagaia (Longa)",
    distancia: 9.5,
    nivel: 7,
    dificuldade: "Média",
    clima: 2,
    temperatura: "< 20º C",
    local: "#",
    capacidade: 30,
    descricao: "#",
    cidade: "#",
    estado: "RS",
    imagem: "#",
    mapa: "#"
  },
  {
    id: 27,
    nome: "Jango e Barragem",
    distancia: 10,
    nivel: 8,
    dificuldade: "Difícil-média",
    clima: 2,
    temperatura: "< 20º C",
    local: "#",
    capacidade: 25,
    descricao: "#",
    cidade: "#",
    estado: "RS",
    imagem: "#",
    mapa: "#"
  },
  {
    id: 28,
    nome: "Limeira",
    distancia: 10,
    nivel: 8,
    dificuldade: "Difícil-média",
    clima: 1,
    temperatura: "< 26º C",
    local: "#",
    capacidade: 30,
    descricao: "#",
    cidade: "#",
    estado: "RS",
    imagem: "#",
    mapa: "#"
  },
  {
    id: 29,
    nome: "Três Quedas",
    distancia: 10,
    nivel: 6,
    dificuldade: "Média",
    clima: 2,
    temperatura: "< 20º C",
    local: "#",
    capacidade: 35,
    descricao: "#",
    cidade: "#",
    estado: "RS",
    imagem: "#",
    mapa: "#"
  },
  {
    id: 30,
    nome: "Cachoeira do Rosa",
    distancia: 11,
    nivel: 8,
    dificuldade: "Difícil-média",
    clima: 2,
    temperatura: "< 20º C",
    local: "#",
    capacidade: 30,
    descricao: "#",
    cidade: "#",
    estado: "RS",
    imagem: "#",
    mapa: "#"
  },
  {
    id: 31,
    nome: "Morro do Elefante (Longa)",
    distancia: 11,
    nivel: 7,
    dificuldade: "Média",
    clima: 3,
    temperatura: "Até 25º C",
    local: "#",
    capacidade: 30,
    descricao: "#",
    cidade: "#",
    estado: "RS",
    imagem: "#",
    mapa: "#"
  },
  {
    id: 32,
    nome: "Cânion da Piruva",
    distancia: 12,
    nivel: 9,
    dificuldade: "Difícil",
    clima: 1,
    temperatura: "< 26º C",
    local: "#",
    capacidade: 37,
    descricao: "#",
    cidade: "#",
    estado: "RS",
    imagem: "#",
    mapa: "#"
  },
  {
    id: 33,
    nome: "São Martinho Zagaia",
    distancia: 12,
    nivel: 8,
    dificuldade: "Média",
    clima: 3,
    temperatura: "Até 25º C",
    local: "6",
    capacidade: 40,
    descricao: "#",
    cidade: "#",
    estado: "RS",
    imagem: "#",
    mapa: "#"
  },
  {
    id: 34,
    nome: "Ferrovia do Vinho",
    distancia: 14,
    nivel: 7,
    dificuldade: "Média",
    clima: 3,
    temperatura: "Até 25º C",
    local: "#",
    capacidade: 25,
    descricao: "#",
    cidade: "#",
    estado: "RS",
    imagem: "#",
    mapa: "#"
  },
  {
    id: 35,
    nome: "São José dos Ausentes",
    distancia: 27,
    nivel: 8,
    dificuldade: "Difícil-média",
    clima: 3,
    temperatura: "Até 25º C",
    local: "#",
    capacidade: 20,
    descricao: "#",
    cidade: "#",
    estado: "RS",
    imagem: "#",
    mapa: "#"
  },
   
  {
    id: 36,
    nome: "Ferrovia do Trigo",
    distancia: "#",
    nivel: 7,
    dificuldade: "Média",
    clima: 3,
    temperatura: "Até 25º C",
    local: "#",
    capacidade: 25,
    descricao: "#",
    cidade: "#",
    estado: "RS",
    imagem: "#",
    mapa: "#"
  },
  {
    id: 37,
    nome: "Peral do Facão",
    distancia: "#",
    nivel: 4,
    dificuldade: "Fácil",
    clima: 3,
    temperatura: "Até 25º C",
    local: "#",
    capacidade: 25,
    descricao: "#",
    cidade: "#",
    estado: "RS",
    imagem: "#",
    mapa: "#"
  },
  {
    id: 38,
    nome: "Pirâmides",
    distancia: "#",
    nivel: 5,
    dificuldade: "Fácil-média",
    clima: 3,
    temperatura: "Até 25º C",
    local: "#",
    capacidade: 25,
    descricao: "#",
    cidade: "#",
    estado: "RS",
    imagem: "#",
    mapa: "#"
  }
];